---

- set_fact:
    registry_volumes:
    - "{{registry_home}}/data:/var/lib/registry"

- set_fact:
    registry_volumes: "{{registry_volumes + [registry_ssl_dir]}}"
  when: registry_ssl and not registry_nginx

- name: Setup and run docker-registry
  docker_container:
    image: "{{registry_image}}"
    name: registry
    env: "{{registry_env}}"
    network_mode: "{{registry_net}}"
    networks: "{{registry_networks}}"
    ports: "{{registry_ports}}"
    pull: true
    restart_policy: always
    volumes: "{{registry_volumes}}"

- name: Copy clean script
  template: src=clean.sh dest={{registry_home}}/clean.sh mode=0755

- include: nginx.yml
  when: registry_nginx
