---

- set_fact:
    registry_volumes:
    - "{{registry_home}}/data:/var/lib/registry"

- set_fact:
    registry_volumes: "{{registry_volumes + [registry_certs_home + ':/certs']}}"
  when: registry_certs_home != ""

- name: Setup and run docker-registry
  docker:
    env: "{{registry_env}}"
    image: "{{registry_image}}"
    name: registry
    net: host
    ports: "{{registry_ports}}"
    restart_policy: always
    state: reloaded
    volumes: "{{registry_volumes}}"
