---

- set_fact:
    registry_volumes:
    - "{{registry_home}}:/var/lib/registry"

- set_fact:
    registry_volumes: "{{registry_volumes + [registry_ssl_dir]}}"
  when: registry_ssl and not registry_nginx

- set_fact:
    registry_env: "{{registry_env|combine(registry_env_auth)}}"
  when: registry_auth_users and not registry_nginx_auth

- name: Prepare registry directory
  file: state=directory path={{registry_home}}

- name: Setup and run docker-registry
  docker_container:
    image: "{{registry_image}}"
    name: registry
    env: "{{registry_env}}"
    network_mode: "{{registry_net}}"
    networks: "{{registry_networks}}"
    ports: "{{registry_ports}}"
    pull: true
    restart_policy: always
    volumes: "{{registry_volumes}}"

- name: Setup basic authentication
  shell: docker run --entrypoint htpasswd {{registry_image}} -Bbn {{item.name}} {{item.password}} >> {{registry_home}}/.htpasswd
  with_items: "{{registry_auth_users}}"
  when: registry_auth_users

- name: Copy clean script
  template: src=clean.sh dest={{registry_home}}/clean.sh mode=0755

- include: nginx.yml
  when: registry_nginx
